home_splash/config/routes.rb
Rails.application.routes.draw do
  resources :backgrounds

  resources :purposes

  resources :locations

  get 'home/index'

  root 'home#index'

end

home_splash/app/models/background.rb
class Background < ActiveRecord::Base
  belongs_to :user

  validates :image_file, presence: true, uniqueness: {scope: :user_id}, length: {in: 2..255}
  #this means that they are unique by user
end

home_splash/app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user

  validates :zip, presence: true, length: {minumum: 5}
end

home_splash/app/models/purpose.rb
class Purpose < ActiveRecord::Base
  belongs_to :user

  validates :goal, presence: true
end

home_splash/app/models/quote.rb
class Quote < ActiveRecord::Base
  validates :quip, presence: true, length: { minimum: 3}, uniqueness: true
  scope :recent, -> (weeks_past=1){ where("created_at > ?", weeks_past.weeks.ago)}
end

home_splash/app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_one :location
  has_many :purposes
  has_many :backgrounds

end

home_splash/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

home_splash/app/controllers/backgrounds_controller.rb
class BackgroundsController < ApplicationController
  before_action :set_background, only: [:show, :edit, :update, :destroy]

  # GET /backgrounds
  # GET /backgrounds.json
  def index
    @backgrounds = Background.all
  end

  # GET /backgrounds/1
  # GET /backgrounds/1.json
  def show
  end

  # GET /backgrounds/new
  def new
    @background = Background.new
  end

  # GET /backgrounds/1/edit
  def edit
  end

  # POST /backgrounds
  # POST /backgrounds.json
  def create
    @background = Background.new(background_params)

    respond_to do |format|
      if @background.save
        format.html { redirect_to @background, notice: 'Background was successfully created.' }
        format.json { render :show, status: :created, location: @background }
      else
        format.html { render :new }
        format.json { render json: @background.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backgrounds/1
  # PATCH/PUT /backgrounds/1.json
  def update
    respond_to do |format|
      if @background.update(background_params)
        format.html { redirect_to @background, notice: 'Background was successfully updated.' }
        format.json { render :show, status: :ok, location: @background }
      else
        format.html { render :edit }
        format.json { render json: @background.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backgrounds/1
  # DELETE /backgrounds/1.json
  def destroy
    @background.destroy
    respond_to do |format|
      format.html { redirect_to backgrounds_url, notice: 'Background was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_background
      @background = Background.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def background_params
      params.require(:background).permit(:user_id, :image_file)
    end
end

home_splash/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    right_now = Time.now
    @current_time = right_now.stamp("Jan 1st 1:00")
    @current_year = Time.now.year


    # Adjust message by time of day
    @greet_message = case right_now.hour
    when 5..11
      "goooooooood mornin"
    when 12..15
      "happy afternooooooon"
    when 16..19
      "good evenin' there, fella"
    when 20..23
      "good night"
    when 0..4
      "hello madrugada"
    end

    @quote = Quote.all.sample.quip
  end
end

home_splash/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:user_id, :address, :city, :state, :zip)
    end
end

home_splash/app/controllers/purposes_controller.rb
class PurposesController < ApplicationController
  before_action :set_purpose, only: [:show, :edit, :update, :destroy]

  # GET /purposes
  # GET /purposes.json
  def index
    @purposes = Purpose.all
  end

  # GET /purposes/1
  # GET /purposes/1.json
  def show
  end

  # GET /purposes/new
  def new
    @purpose = Purpose.new
  end

  # GET /purposes/1/edit
  def edit
  end

  # POST /purposes
  # POST /purposes.json
  def create
    @purpose = Purpose.new(purpose_params)

    respond_to do |format|
      if @purpose.save
        format.html { redirect_to @purpose, notice: 'Purpose was successfully created.' }
        format.json { render :show, status: :created, location: @purpose }
      else
        format.html { render :new }
        format.json { render json: @purpose.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purposes/1
  # PATCH/PUT /purposes/1.json
  def update
    respond_to do |format|
      if @purpose.update(purpose_params)
        format.html { redirect_to @purpose, notice: 'Purpose was successfully updated.' }
        format.json { render :show, status: :ok, location: @purpose }
      else
        format.html { render :edit }
        format.json { render json: @purpose.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purposes/1
  # DELETE /purposes/1.json
  def destroy
    @purpose.destroy
    respond_to do |format|
      format.html { redirect_to purposes_url, notice: 'Purpose was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purpose
      @purpose = Purpose.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purpose_params
      params.require(:purpose).permit(:user_id, :goal)
    end
end

home_splash/app/helpers/application_helper.rb
module ApplicationHelper
end

home_splash/app/helpers/backgrounds_helper.rb
module BackgroundsHelper
end

home_splash/app/helpers/home_helper.rb
module HomeHelper
end

home_splash/app/helpers/locations_helper.rb
module LocationsHelper
end

home_splash/app/helpers/purposes_helper.rb
module PurposesHelper
end

home_splash/app/views/backgrounds/_form.html.erb
<%= form_for(@background) do |f| %>
  <% if @background.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@background.errors.count, "error") %> prohibited this background from being saved:</h2>

      <ul>
      <% @background.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :image_file %><br>
    <%= f.text_field :image_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

home_splash/app/views/backgrounds/edit.html.erb
<h1>Editing Background</h1>

<%= render 'form' %>

<%= link_to 'Show', @background %> |
<%= link_to 'Back', backgrounds_path %>

home_splash/app/views/backgrounds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Backgrounds</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Image file</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @backgrounds.each do |background| %>
      <tr>
        <td><%= background.user %></td>
        <td><%= background.image_file %></td>
        <td><%= link_to 'Show', background %></td>
        <td><%= link_to 'Edit', edit_background_path(background) %></td>
        <td><%= link_to 'Destroy', background, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Background', new_background_path %>

home_splash/app/views/backgrounds/new.html.erb
<h1>New Background</h1>

<%= render 'form' %>

<%= link_to 'Back', backgrounds_path %>

home_splash/app/views/backgrounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @background.user %>
</p>

<p>
  <strong>Image file:</strong>
  <%= @background.image_file %>
</p>

<%= link_to 'Edit', edit_background_path(@background) %> |
<%= link_to 'Back', backgrounds_path %>

home_splash/app/views/home/index.html.erb
<div id ="main" class="shadowed">
  <h1 id ="clock"><%= @current_time %></h1>
  <p id ="greeting"><%= @greet_message %></p>
</div>

<div id ="quote" class="shadowed">
  <%= @quote %>
</div>

home_splash/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HomeSplash</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Roboto:500italic,400|Raleway' rel='stylesheet' type='text/css'>
</head>
<body>
  <div id="clearance_links">
    <% if signed_in? %>
      Hey there, <%= current_user.email %>
      <%= link_to (fa_icon "sign-out", text: "Sign Out?"), sign_out_path, method: :delete %>
    <% else %>
      <%= link_to (fa_icon "users", text: "Sign In"), sign_in_path %>
    <% end %>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
  </div>

  <%= yield %>

  <%= render 'shared/footer' %>

</body>
</html>

home_splash/app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

home_splash/app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

home_splash/app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.user %></td>
        <td><%= location.address %></td>
        <td><%= location.city %></td>
        <td><%= location.state %></td>
        <td><%= location.zip %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

home_splash/app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

home_splash/app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @location.user %>
</p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @location.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @location.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @location.zip %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

home_splash/app/views/purposes/_form.html.erb
<%= form_for(@purpose) do |f| %>
  <% if @purpose.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purpose.errors.count, "error") %> prohibited this purpose from being saved:</h2>

      <ul>
      <% @purpose.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :goal %><br>
    <%= f.text_field :goal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

home_splash/app/views/purposes/edit.html.erb
<h1>Editing Purpose</h1>

<%= render 'form' %>

<%= link_to 'Show', @purpose %> |
<%= link_to 'Back', purposes_path %>

home_splash/app/views/purposes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Purposes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Goal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purposes.each do |purpose| %>
      <tr>
        <td><%= purpose.user %></td>
        <td><%= purpose.goal %></td>
        <td><%= link_to 'Show', purpose %></td>
        <td><%= link_to 'Edit', edit_purpose_path(purpose) %></td>
        <td><%= link_to 'Destroy', purpose, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purpose', new_purpose_path %>

home_splash/app/views/purposes/new.html.erb
<h1>New Purpose</h1>

<%= render 'form' %>

<%= link_to 'Back', purposes_path %>

home_splash/app/views/purposes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @purpose.user %>
</p>

<p>
  <strong>Goal:</strong>
  <%= @purpose.goal %>
</p>

<%= link_to 'Edit', edit_purpose_path(@purpose) %> |
<%= link_to 'Back', purposes_path %>

home_splash/app/views/shared/_footer.html.erb
<div id="footer">
  &copy; <%= @current_year %>
  <%= fa_icon 'github' %>
  <a href="https://github.com/mikevallano/home-splash" target="_blank">source code</a>
</div>

home_splash/app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

home_splash/app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t('.title') %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t('.sign_in'), sign_in_path %>
    </div>
  <% end %>
</div>